[tool.poetry]
name = "adaptive-hockey-federation"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{ include = "adaptive_hockey_federation" }]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.6"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"

[tool.poetry.group.test.dependencies]
flake8 = "^6.1.0"
flake8-isort = "^6.1.0"
mypy = "^1.5.1"
flake8-django = "^1.4"


[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
