name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: | 
        python -m pip install --no-cache-dir poetry==1.6.1 \
        && poetry config virtualenvs.in-project true \
        && poetry install --without dev --with test

    - name: Test with flake8 and django tests
      run: |
        poetry install \
        && flake8 adaptive_hockey_federation